import type { HomePageData } from '../../types'

export const data: HomePageData = {
  routeKey: 'home',
  seo: {
    title: 'Marek Chodacki | Fullstack Vue, Nuxt, Astro Developer',
  },
  h1: 'Three competencies. | One person. | Zero complications.',
  p1: 'I combine the skills of an App and Web Developer, a WordPress and WooCommerce Expert, and an SEO Specialist. I create solutions from backend to frontend, ensuring the performance and optimization of each website.',
  p2: 'I can develop dedicated applications in Vue, Nuxt, and Astro, as well as design scalable systems based on PHP and MySQL. I understand design not only from a coding perspective but also from a visibility perspective.',
  p3: 'Instead of three people, you have one partner. I will build a website, app, or online store for you, optimize them for Google search, and take care of the technical details that will increase your sales.',
  p4: 'This will help your business grow faster,<br />and you save time and money.',
  callButton: {
    url: 'tel:+48506788894',
    image: '/assets/icons/btn_phone.svg',
    alt: 'Call me',
    text: 'Call me',
  },
  mailButton: {
    url: '/en/contact',
    image: '/assets/icons/btn_mail.svg',
    alt: 'Contact - Send mail',
    text: 'Send mail',
  },
  projects: [
    {
      url: '/en/webapps',
      rel: 'noopener noreferrer',
      title: 'Web Applications',
      image: '/assets/icons/cat_webapps.svg',
      alt: 'Web Applications Design',
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'Vue',
        'Nuxt',
        'Astro',
        'Node',
        'TypeScript',
        'Supabase',
        'REST API',
        'Tailwind',
        'Git',
        'CI/CD',
      ],
    },
    {
      url: '/en/websites-stores',
      rel: 'noopener noreferrer',
      title: 'Websites &amp;&nbsp;E-Commerce',
      image: '/assets/icons/cat_websites.svg',
      alt: 'Website &amp;&nbsp;E-Commerce Design',
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'WordPress',
        'WooCommerce',
        'PHP',
        'MySQL',
        'Personalizacja',
        'Integracje',
        'Wydajność',
      ],
    },
    {
      url: '/en/seo-positioning',
      rel: 'noopener noreferrer',
      title: 'SEO &amp;&nbsp;Positioning',
      image: '/assets/icons/cat_seo.svg',
      alt: 'SEO Optimization and Website Positioning',
      label: 'Strategies &amp;&nbsp;tools',
      techs: [
        'SEO On-Page',
        'SEO Techniczne',
        'Audyt SEO',
        'Content',
        'Link Building',
        'Analytics',
        'Search Console',
        'Ahrefs',
        'Semrush',
        'PageSpeed',
      ],
    },
  ],
}
