import type { ProjectPageData } from '../../types'

export const data: ProjectPageData = {
  routeKey: 'seo',
  seo: {
    title: 'SEO Optimization and Website Positioning | Marek Chodacki',
  },
  h1: 'SEO &amp;&nbsp;Positioning',
  projects: [
    {
      title: '2021–2025 | Client Projects',
      url: '',
      rel: '',
      anchor: '',
      description: [
        'SEO optimization as an integral part of website and e‑commerce builds',
        'Technical SEO audits and implementation of on‑site best practices during development',
        'Performance, information architecture, and content optimization aligned with Google guidelines',
        'SEO advisory for long‑term visibility and sustainable growth',
        'Advanced SEO analytics and reporting',
      ],
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'Google Analytics',
        'Google Search Console',
        'Screaming Frog',
        'PageSpeed Insights',
        'Schema.org',
        'Yoast SEO / Rank Math',
        'Excel & Google Sheets',
      ],
    },
    {
      title: '2019–2021 | K2 Precise S.A. | Warsaw',
      url: 'https://k2precise.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'Visit website',
      description: [
        'Creation and optimization of blog content following SEO best practices',
        'Development of video metadata and assets: titles, descriptions, transcripts/captions',
        'Comprehensive on‑page optimization: titles, headings, metadata, content structure',
        'Ensured linguistic consistency and brand voice across multichannel communications',
      ],
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'YouTube Studio',
        'Google Analytics',
        'Google Search Console',
        'Google Keyword Planner',
        'Ahrefs',
        'Screaming Frog',
      ],
    },
    {
      title: '2017–2019 | Pro‑European Education Center | Lublin',
      url: 'https://ckp.lublin.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'Visit website',
      description: [
        'Conducted trainings on website creation, SEO optimization, and search positioning within EU‑funded programs',
        'Collaboration on on‑site and off‑site optimization for the corporate website',
        'Support for promotional and marketing initiatives',
        'Led analytics workshops',
        'Prepared and delivered educational materials',
      ],
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'Google Analytics',
        'Google Search Console',
        'Google Keyword Planner',
        'Excel & Google Sheets',
        'PowerPoint',
      ],
    },
    {
      title: '2015–2017 | Performance Media | Lublin',
      url: 'https://performancegroup.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'Visit website',
      description: [
        'Planned and executed SEO strategies for agency client websites',
        'Technical SEO audits: content, performance, and site architecture analysis',
        'Campaign performance reporting and insights',
        'Collaboration with the IT team on bespoke software development',
        'Process automation through custom PHP scripting',
        'Designed specialized spreadsheets with automated multi‑source data consolidation, significantly reducing analysis, reporting, and daily operational time',
      ],
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'Google Analytics',
        'Google Search Console',
        'Ahrefs',
        'Majestic SEO',
        'SEMStorm',
        'Screaming Frog',
        'PHP',
        'Excel & Google Sheets',
      ],
    },
  ],
}
