import type { ProjectPageData } from '../../types'

export const data: ProjectPageData = {
  routeKey: 'websites',
  seo: {
    title: 'Websites and E-Commerce Stores | Marek Chodacki',
  },
  h1: 'Websites &amp;&nbsp;E-Commerce',
  projects: [
    {
      title: '2025 | Winnica Koniczynowe Wzgórze | Puławy',
      rel: 'noopener noreferrer nofollow',
      description: [
        'End-to-end visual identity: logo, labels, packaging prints, branded apparel',
        'Branding consultations and enforcement of consistent visual communication',
        'Print-ready production files and coordination with the print house',
        'WooCommerce store implementation (OceanWP theme) - in progress; focused on streamlined online wine sales and owner-friendly management',
      ],
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'WordPress',
        'WooCommerce',
        'OceanWP',
        'PHP',
        'MySQL',
        'Photoshop',
        'Illustrator',
      ],
    },
    {
      title: '2024 | WaterFamily | Radom',
      url: 'https://waterfamily.com.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'View store',
      description: [
        'Full WooCommerce rollout (Neve theme) tailored for a 200+ product catalog',
        'Technical and performance optimization: hosting, SSL, DNS, CDN',
        'SEO copywriting: marketing taglines, web content, product pages, blog articles',
        'Integrations with payment gateways, couriers, and the Ceneo price comparison engine',
        'Offline brand collateral design: leaflets, banners, business cards, storefront signage',
      ],
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'WordPress',
        'WooCommerce',
        'Neve',
        'PHP',
        'MySQL',
        'Google Analytics',
        'Google Search Console',
        'Google Keyword Planner',
        'Photoshop',
      ],
    },
    {
      title: '2023 | HurtGSM | Radom',
      url: 'https://hurtgsm.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'View store',
      description: [
        'Scalable WooCommerce deployment (Porto theme) with custom front‑end and plugin enhancements',
        'Multi‑system integrations: shipping (InPost, Pocztex, Żabka, Orlen, Poczta Polska), payments (Tpay), and the Sellasist multichannel platform',
        'Day‑to‑day administration and monitoring of external sales channel synchronizations',
        'Product photography and post‑production (360° Orbitvu Alphashot)',
        'Operations and maintenance of a 4,500+ product catalog',
      ],
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'WordPress',
        'WooCommerce',
        'Porto',
        'PHP',
        'MySQL',
        'SellAsist',
        'Google Analytics',
        'Google Search Console',
        'Ubersuggest',
        'Alphashot Editor Pro',
        'Photoshop',
      ],
    },
    {
      title: '2022 | WedzIGrilluj | Lublin',
      url: 'https://wedzigrilluj.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'View store',
      description: [
        'Migration from PrestaShop to WooCommerce + 301 redirects (preserving Google rankings)',
        'Store design and implementation (Maison theme) optimized for UX and conversion',
        'Comprehensive SEO (on‑site + off‑site) and content strategy driven by keyword research',
        'Speed and performance optimization for UX and SEO outcomes',
        'SEO reporting and growth consulting',
      ],
      label: 'Technologies &amp;&nbsp;tools',
      techs: [
        'WordPress',
        'WooCommerce',
        'PrestaShop',
        'Maison',
        'PHP',
        'MySQL',
        'Google Analytics',
        'Google Search Console',
        'Google Keyword Planner',
        'Google PageSpeed Insights',
        'GTMetrix',
      ],
    },
    {
      title: '2021 | ClubGarden | Radom',
      url: 'https://clubgarden.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'View store',
      description: [
        'WooCommerce implementation (Unero theme) with a modern, conversion‑oriented design',
        'Complete technical setup: hosting, domain, SSL, DNS, FTP',
        'SEO campaign and long‑term search growth initiatives to boost visibility and organic traffic',
      ],
      label: 'Technologies &amp;&nbsp;tools',
      techs: ['WordPress', 'WooCommerce', 'Unero', 'PHP', 'MySQL', 'Photoshop'],
    },
  ],
}
