import type { HomePageData } from '../../types'

export const data: HomePageData = {
  routeKey: 'home',
  seo: {
    title: 'Marek Chodacki | Programista Fullstack',
  },
  h1: 'Trzy kompetencje. | Jeden człowiek. | Zero komplikacji.',
  p1: 'Łączę w&nbsp;sobie kompetencje App i&nbsp;Web Developera, Eksperta WordPress i&nbsp;WooCommerce oraz&nbsp;Specjalisty SEO. Tworzę rozwiązania od&nbsp;backendu po&nbsp;frontend, dbając o&nbsp;wydajność i&nbsp;optymalizację każdej witryny.',
  p2: 'Potrafię rozwijać zarówno dedykowane aplikacje w&nbsp;Vue, Nuxt czy&nbsp;Astro, jak&nbsp;i&nbsp;projektować skalowalne systemy w&nbsp;oparciu o&nbsp;PHP i&nbsp;MySQL.<br />Rozumiem projektowanie nie&nbsp;tylko od&nbsp;strony kodu, ale&nbsp;i&nbsp;widoczności w&nbsp;sieci.',
  p3: 'Zamiast trzech osób - masz jednego partnera. Zbuduję dla&nbsp;Ciebie stronę www, aplikację lub sklep internetowy, zajmę&nbsp;się ich optymalizacją pod&nbsp;wyszukiwarkę Google i&nbsp;zadbam o&nbsp;techniczne szczegóły, które zwiększą Twoją sprzedaż.',
  p4: 'Dzięki temu Twój biznes urośnie szybciej,<br class="mobile-hidden" />a&nbsp;Ty oszczędzisz czas i&nbsp;pieniądze.',
  callButton: {
    url: 'tel:+48506788894',
    image: '/assets/icons/btn_phone.svg',
    alt: 'Zadzwoń',
    text: 'Zadzwoń',
  },
  mailButton: {
    url: '/kontakt',
    image: '/assets/icons/btn_mail.svg',
    alt: 'Kontakt - Wyślij mail',
    text: 'Wyślij mail',
  },
  projects: [
    {
      url: '/aplikacje-webowe',
      rel: 'noopener noreferrer',
      title: 'Aplikacje webowe',
      image: '/assets/icons/cat_webapps.svg',
      alt: 'Tworzenie aplikacji webowych',
      label: 'Technologie i&nbsp;narzędzia',
      techs: [
        'Vue',
        'Nuxt',
        'Astro',
        'Node',
        'TypeScript',
        'Supabase',
        'REST API',
        'Tailwind',
        'Git',
        'CI/CD',
      ],
    },
    {
      url: '/strony-sklepy',
      rel: 'noopener noreferrer',
      title: 'Strony i&nbsp;Sklepy internetowe',
      image: '/assets/icons/cat_websites.svg',
      alt: 'Projektowanie stron i sklepów internetowych',
      label: 'Technologie i&nbsp;narzędzia',
      techs: [
        'WordPress',
        'WooCommerce',
        'PHP',
        'MySQL',
        'Personalizacja',
        'Integracje',
        'Wydajność',
      ],
    },
    {
      url: '/seo-pozycjonowanie',
      rel: 'noopener noreferrer',
      title: 'SEO i&nbsp;Pozycjonowanie',
      image: '/assets/icons/cat_seo.svg',
      alt: 'Optymalizacja SEO i Pozycjonowanie stron internetowych',
      label: 'Strategie i&nbsp;narzędzia',
      techs: [
        'SEO On-Page',
        'SEO Techniczne',
        'Audyt SEO',
        'Content',
        'Link Building',
        'Analytics',
        'Search Console',
        'Ahrefs',
        'Semrush',
        'PageSpeed',
      ],
    },
  ],
}
