import type { ProjectPageData } from '../../types'

export const data: ProjectPageData = {
  routeKey: 'websites',
  seo: {
    title: 'Projektowanie stron www i sklepów internetowych | Marek Chodacki',
  },
  h1: 'Strony i Sklepy',
  projects: [
    {
      title: '2025 | Winnica Koniczynowe Wzgórze | Puławy',
      rel: 'noopener noreferrer nofollow',
      description: [
        'Stworzenie kompletnej identyfikacji wizualnej: logo, etykiety, nadruki, odzież firmowa',
        'Konsultacje brandingowe i pilnowanie spójnej komunikacji wizualnej',
        'Przygotowanie materiałów produkcyjnych do druku i koordynacja z drukarnią',
        'Wdrożenie sklepu internetowego WooCommerce (motyw OceanWP) - w trakcie realizacji, nacisk na sprzedaż wina online i prostotę obsługi przez właściciela',
      ],
      label: 'Technologie i&nbsp;narzędzia',
      techs: [
        'WordPress',
        'WooCommerce',
        'OceanWP',
        'PHP',
        'MySQL',
        'Photoshop',
        'Illustrator',
      ],
    },
    {
      title: '2024 | WaterFamily | Radom',
      url: 'https://waterfamily.com.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'Zobacz sklep',
      description: [
        'Kompleksowe wdrożenie sklepu internetowego WooCommerce (motyw Neve) dostosowanego do sprzedaży 200+ produktów',
        'Optymalizacja techniczna i wydajnościowa: hosting, SSL, DNS, CDN',
        'SEO copywriting: hasła marketingowe, treści stron, treści produktowe, treści blogowe',
        'Integracja z systemami płatności, firmami kurierskimi i porównywarką cen Ceneo',
        'Projekt materiałów offline wspierających identyfikację marki: ulotki, banery, wizytówki, szyld',
      ],
      label: 'Technologie i&nbsp;narzędzia',
      techs: [
        'WordPress',
        'WooCommerce',
        'Neve',
        'PHP',
        'MySQL',
        'Google Analytics',
        'Google Search Console',
        'Google Keyword Planner',
        'Photoshop',
      ],
    },
    {
      title: '2023 | HurtGSM | Radom',
      url: 'https://hurtgsm.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'Zobacz sklep',
      description: [
        'Wdrożenie skalowalnego sklepu WooCommerce (motyw Porto) z dedykowanymi modyfikacjami front-endu i wtyczek',
        'Integracja z wieloma systemami: kurierzy (InPost, Pocztex, Żabka, Orlen, PP), płatności (Tpay), platforma multichannel Sellasist',
        'Codzienna administracja, monitorowanie synchronizacji zewnętrznych systemów sprzedaży',
        'Wykonywanie i edycja zdjęć produktowych (360° Orbitvu Alphashot)',
        'Administracja i aktualizacja 4500+ produktów w sklepie',
      ],
      label: 'Technologie i&nbsp;narzędzia',
      techs: [
        'WordPress',
        'WooCommerce',
        'Porto',
        'PHP',
        'MySQL',
        'SellAsist',
        'Google Analytics',
        'Google Search Console',
        'Ubersuggest',
        'Alphashot Editor Pro',
        'Photoshop',
      ],
    },
    {
      title: '2022 | WedzIGrilluj | Lublin',
      url: 'https://wedzigrilluj.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'Zobacz sklep',
      description: [
        'Migracja PrestaShop do WooCommerce + przekierowaia 301 (utrzymanie pozycji w Google)',
        'Projekt i wdrożenie sklepu (motyw Maison) zoptymalizowanego pod UX i konwersję',
        'Kompleksowe SEO (on-site + off-site) oraz strategia contentowa oparta o keyword research',
        'Optymalizacja prędkości i wydajności sklepu pod kątem doświadczeń użytkownika i SEO',
        'Raportowanie działań SEO i konsultacje rozwojowe',
      ],
      label: 'Technologie i&nbsp;narzędzia',
      techs: [
        'WordPress',
        'WooCommerce',
        'PrestaShop',
        'Maison',
        'PHP',
        'MySQL',
        'Google Analytics',
        'Google Search Console',
        'Google Keyword Planner',
        'Google PageSpeed Insights',
        'GTMetrix',
      ],
    },
    {
      title: '2021 | ClubGarden | Radom',
      url: 'https://clubgarden.pl/',
      rel: 'noopener noreferrer nofollow',
      anchor: 'Zobacz sklep',
      description: [
        'Wdrożenie sklepu WooCommerce (motyw Unero) z nowoczesnym designem',
        'Pełna konfiguracja techniczna: hosting, domena, SSL, DNS, FTP',
        'Kampania SEO i długoterminowe działania pozycjonujące dla zwiększenia widoczności w wyszukiwarce i ruchu organicznego',
      ],
      label: 'Technologie i&nbsp;narzędzia',
      techs: ['WordPress', 'WooCommerce', 'Unero', 'PHP', 'MySQL', 'Photoshop'],
    },
  ],
}
